setwd("/Users/ellaelchik/Documents/studies/r_programming")
data=read.table("household_power_consumption.txt", header=TRUE, sep=";", dec=".", stringsAsFactors=FALSE)

data$Global_active_power=as.numeric(data$Global_active_power)
data$Global_reactive_power=as.numeric(data$Global_reactive_power)
data$Voltage=as.numeric(data$Voltage)
data$Global_intensity=as.numeric(data$Global_intensity)
data$Sub_metering_1=as.numeric(data$Sub_metering_1)
data$Sub_metering_2=as.numeric(data$Sub_metering_2)
data$Sub_metering_3=as.numeric(data$Sub_metering_3)
data$Date1<-as.Date(data$Date, format="%d/%m/%Y")
data$Time1<-strptime(data$Time, format="%H:%M:%S")
data$Datetime<-as.POSIXct(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")

subset=subset(data, data$Date1>="2007-02-01" & data$Date1<="2007-02-02")
plot(subset$Datetime, subset$Global_active_power,ylab="Global Active Power (kilowatts)", xlab="", type="l")
